name: SA3 checker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for student name
        # we have to ignore the two occurrences in this file
        run: if [ $(grep -ri "student name" | wc -l) -gt 2 ]; then echo 'student name detected!'; exit 1; fi

      - name: Check for node_modules
        run: if [ -d node_modules ]; then echo 'node_modules folder detected!'; exit 2; fi

      - name: Check for npm usage
        run: if [ -f package-lock.json ]; then echo 'npm usage detected!'; exit 3; fi

  node-tests:
    runs-on: ubuntu-latest
    needs: basic-checks
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        if: ${{ hashFiles('**/package.json') != '' }}
        run: yarn install

      - name: Run tests
        if: ${{ hashFiles('**/package.json') != '' }}
        continue-on-error: true
        run: yarn test

  notify-checkbot:
    runs-on: ubuntu-latest
    needs: [basic-checks, node-tests]
    if: ${{ contains(github.event.head_commit.message, 'please check') }}
    steps:
      - name: Ping checkbot
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} --header 'Content-Type: application/json' \
          -d '{\"content\": \"${{ github.event.pusher.name }} has pushed to ${{ github.repositoryUrl }}: ${{ github.event.head_commit.message }}\"}'
